language: android
dist: trusty

before_install:
  - wget http://services.gradle.org/distributions/gradle-5.1.1-bin.zip
  - unzip gradle-5.1.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.1.1
  - export PATH=$GRADLE_HOME/bin:$PATH
#  - yes | sdkmanager "platforms;android-28"
#  - ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk -a --no-ui --filter tool,platform-tool,build-tools-28.0.3

script:
  - gradle lint
  - gradle assembleDebug

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
